import type {
  CoachProfile,
  AthleteProfile,
  CoachPackage,
  Application,
  Subscription,
  TrainingProgram,
  VideoSubmission,
  MessageThread,
  BillingSummary,
} from './types'

export const MOCK_COACHES: CoachProfile[] = [
  {
    id: 'coach-1',
    userId: 'user-coach-1',
    name: 'Marcus Eaton',
    avatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=400&h=400&fit=crop',
    headline: 'Former NCAA D1 thrower. Coaching discus and shot put at the collegiate and post-collegiate level.',
    bio: 'Fifteen years of competitive experience at the D1 and elite club level. I work with athletes who are serious about the technical side of throwing — position, timing, sequence. I build programming around where you actually are, not where you think you are.',
    location: 'Austin, TX',
    specialties: ['discus', 'shot_put'],
    currentRole: 'Club Throws Coach, Austin Track Club',
    pastExperience: ['USATF Level 2 Certified', 'Former D1 All-American, discus', '8 years coaching at the collegiate level'],
    achievements: ['3x conference champion', 'NCAA Indoor qualifier', 'USATF Club Team Championships, 2019'],
    socialLinks: [{ platform: 'instagram', url: '#' }],
    packages: [],
    intakeMode: 'application',
    intakeQuestions: [
      'What are your current personal records for your primary events?',
      'What are your goals for the next 12 months?',
      'Describe your current training setup — access to implements, lifting facility, track, etc.',
    ],
    maxAthletes: 12,
    activeAthletes: 9,
    isOpen: true,
    estimatedResponseTime: '24 hours',
    videoTurnaround: '48-72 hours',
    policies: 'Monthly rolling commitment. First month is evaluation period — I assess your mechanics, training history, and goals before setting full program.',
    rating: 4.9,
    reviewCount: 34,
    verificationStatus: 'verified',
    createdAt: '2023-03-12',
  },
  {
    id: 'coach-2',
    userId: 'user-coach-2',
    name: 'Priya Nair',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop',
    headline: 'Hammer and javelin specialist. USATF coaching certification. 12 years competitive experience.',
    bio: 'I specialize in rotational mechanics for hammer and the approach-plant sequence for javelin. My athletes range from high school to national-level competitors. I provide weekly programming with video review and bi-weekly check-in calls.',
    location: 'Portland, OR',
    specialties: ['hammer', 'javelin'],
    currentRole: 'Independent Throws Coach',
    pastExperience: ['USATF Level 2 Certified', 'Former collegiate hammer thrower', 'NSCA-CSCS certified'],
    achievements: ['National age group qualifier (hammer)', 'Masters World Championship participant'],
    socialLinks: [],
    packages: [],
    intakeMode: 'instant',
    maxAthletes: 18,
    activeAthletes: 11,
    isOpen: true,
    estimatedResponseTime: '12 hours',
    videoTurnaround: '24-48 hours',
    policies: 'Cancel anytime. No long-term contract required. I do require a 2-week minimum to properly assess and adjust programming.',
    rating: 4.8,
    reviewCount: 52,
    verificationStatus: 'verified',
    createdAt: '2022-09-01',
  },
  {
    id: 'coach-3',
    userId: 'user-coach-3',
    name: 'James Okonkwo',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop',
    headline: 'Shot put and discus. Former professional thrower. Elite-level programming and biomechanical coaching.',
    bio: 'I competed professionally from 2010 to 2021. Now I coach full time. I work with a small number of serious athletes — mostly collegiate and post-collegiate level. My programming is periodized, data-driven, and specific. I will not take on athletes who are not ready to commit.',
    location: 'Atlanta, GA',
    specialties: ['shot_put', 'discus'],
    currentRole: 'Private Throws Coach',
    pastExperience: ['Former professional thrower', 'USATF Level 3 Elite Certification', 'Sports Science background'],
    achievements: ['National top-10 (shot put, 2016-2020)', 'Olympic Trials qualifier x3', 'Diamond League invite, 2018'],
    socialLinks: [{ platform: 'instagram', url: '#' }, { platform: 'twitter', url: '#' }],
    packages: [],
    intakeMode: 'application',
    intakeQuestions: [
      'What is your current shot put PR and when was it set?',
      'What does your current strength training look like?',
      'Have you worked with a remote coach before? What worked or did not work?',
      'What is your competitive schedule for the next 12 months?',
    ],
    maxAthletes: 8,
    activeAthletes: 7,
    isOpen: true,
    estimatedResponseTime: '48 hours',
    videoTurnaround: '72 hours',
    policies: 'Minimum 3-month commitment. I work with athletes who are prepared to put in the work. All athletes must have video from at least 3 sessions within the first 2 weeks.',
    rating: 5.0,
    reviewCount: 18,
    verificationStatus: 'verified',
    createdAt: '2023-06-15',
  },
  {
    id: 'coach-4',
    userId: 'user-coach-4',
    name: 'Sarah Chen',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop',
    headline: 'Youth and high school throws development. Shot put, discus, and javelin fundamentals.',
    bio: 'I work primarily with athletes ages 14-22 who are building their foundation. I specialize in teaching proper mechanics from the ground up — no bad habits, no shortcuts. Technique first, power after.',
    location: 'Denver, CO',
    specialties: ['shot_put', 'discus', 'javelin'],
    currentRole: 'High School Track Coach + Private Coach',
    pastExperience: ['8 years high school coaching', 'USATF Level 1 Certified', 'Former D3 thrower'],
    achievements: ['Multiple state qualifiers coached', '3 state champions coached (HS level)'],
    socialLinks: [],
    packages: [],
    intakeMode: 'instant',
    maxAthletes: 20,
    activeAthletes: 14,
    isOpen: true,
    estimatedResponseTime: '24 hours',
    videoTurnaround: '48 hours',
    policies: 'Month-to-month. Great fit for athletes in season or off-season development. Open to working with parents directly for youth athletes.',
    rating: 4.7,
    reviewCount: 41,
    verificationStatus: 'verified',
    createdAt: '2022-01-20',
  },
]

export const MOCK_PACKAGES: CoachPackage[] = [
  {
    id: 'pkg-1',
    coachId: 'coach-1',
    name: 'Full Remote Coaching',
    description: 'Complete coaching relationship. Weekly programming, video review, messaging access, and monthly check-in call.',
    price: 285,
    billingCadence: 'monthly',
    includes: ['Weekly periodized programming', '4 video reviews per month', 'Messaging access', 'Monthly call'],
    videoReviewsPerMonth: 4,
    messagingAccess: true,
    programUpdates: true,
    athleteCap: 12,
    isVisible: true,
  },
  {
    id: 'pkg-2',
    coachId: 'coach-1',
    name: 'Programming Only',
    description: 'Structured weekly programming without video review. Best for athletes who have an on-site coach or just need structured periodization.',
    price: 95,
    billingCadence: 'monthly',
    includes: ['Weekly periodized programming', 'Session notes and cues', 'Monthly program adjustment'],
    videoReviewsPerMonth: 0,
    messagingAccess: false,
    programUpdates: true,
    isVisible: true,
  },
  {
    id: 'pkg-3',
    coachId: 'coach-1',
    name: 'Video Critique',
    description: 'Submit a video, get a detailed technical breakdown within 48 hours.',
    price: 65,
    billingCadence: 'one_time',
    includes: ['One video submission', 'Full technical breakdown', 'Drill recommendations'],
    videoReviewsPerMonth: 1,
    messagingAccess: false,
    programUpdates: false,
    isVisible: true,
  },
  {
    id: 'pkg-4',
    coachId: 'coach-2',
    name: 'Full Coaching — Hammer + Javelin',
    description: 'Complete remote coaching package specialized for hammer and javelin athletes.',
    price: 240,
    billingCadence: 'monthly',
    includes: ['Periodized programming', '4 video reviews', 'Unlimited messaging', 'Bi-weekly call'],
    videoReviewsPerMonth: 4,
    messagingAccess: true,
    programUpdates: true,
    athleteCap: 18,
    isVisible: true,
  },
  {
    id: 'pkg-5',
    coachId: 'coach-3',
    name: 'Elite Performance Package',
    description: 'For serious collegiate and post-collegiate competitors. Full service coaching with biomechanical analysis.',
    price: 450,
    billingCadence: 'monthly',
    includes: ['Daily programming', '8 video reviews per month', 'Priority messaging', 'Weekly call', 'Competition planning'],
    videoReviewsPerMonth: 8,
    messagingAccess: true,
    programUpdates: true,
    hourlyRate: 120,
    athleteCap: 8,
    isVisible: true,
  },
]

export const MOCK_ATHLETES: AthleteProfile[] = [
  {
    id: 'athlete-1',
    userId: 'user-athlete-1',
    name: 'Tyler Rhodes',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop',
    age: 22,
    location: 'Columbus, OH',
    primaryEvent: 'shot_put',
    secondaryEvents: ['discus'],
    prs: { shot_put: '16.24m', discus: '48.10m' },
    level: 'collegiate',
    schoolOrClub: 'Ohio State University',
    height: "6'2\"",
    weight: '248 lbs',
    trainingAge: 5,
    goals: 'Qualify for NCAA Championships. Break 17m in shot put by end of outdoor season.',
    coachingPreferences: ['full_coaching', 'video_critique'],
    budget: '$200-350/month',
    bio: 'Current NCAA D1 athlete. Work with remote coach for technical development outside of normal practice.',
    videos: [],
    currentCoachId: 'coach-1',
    currentPackageId: 'pkg-1',
    visibilitySettings: { publicProfile: true, showPRs: true, showVideos: false },
    createdAt: '2024-01-08',
  },
  {
    id: 'athlete-2',
    userId: 'user-athlete-2',
    name: 'Kenzie Park',
    avatar: 'https://images.unsplash.com/photo-1488426862026-3ee34a7d66df?w=400&h=400&fit=crop',
    age: 19,
    location: 'Sacramento, CA',
    primaryEvent: 'hammer',
    secondaryEvents: [],
    prs: { hammer: '52.40m' },
    level: 'high_school',
    schoolOrClub: 'Granite Bay HS',
    height: "5'8\"",
    weight: '165 lbs',
    trainingAge: 2,
    goals: 'College recruitment. Throw 58m by end of senior season.',
    coachingPreferences: ['full_coaching'],
    budget: '$150-250/month',
    bio: 'Junior year. No hammer program at my school — doing everything remote.',
    videos: [],
    currentCoachId: 'coach-2',
    currentPackageId: 'pkg-4',
    visibilitySettings: { publicProfile: true, showPRs: true, showVideos: true },
    createdAt: '2024-03-15',
  },
  {
    id: 'athlete-3',
    userId: 'user-athlete-3',
    name: 'Daniel Farris',
    avatar: 'https://images.unsplash.com/photo-1547425260-76bcadfb4f2c?w=400&h=400&fit=crop',
    age: 26,
    location: 'Portland, OR',
    primaryEvent: 'discus',
    secondaryEvents: ['shot_put'],
    prs: { discus: '55.80m', shot_put: '17.50m' },
    level: 'post_collegiate',
    schoolOrClub: 'Oregon Track Club',
    height: "6'3\"",
    weight: '265 lbs',
    trainingAge: 9,
    goals: 'Olympic Trials standard. Break 60m in discus.',
    coachingPreferences: ['full_coaching', 'programming'],
    budget: '$400-600/month',
    bio: 'Post-collegiate, self-funded. Training for Olympic Trials cycle.',
    videos: [],
    currentCoachId: 'coach-1',
    currentPackageId: 'pkg-1',
    visibilitySettings: { publicProfile: false, showPRs: true, showVideos: false },
    createdAt: '2023-11-20',
  },
]

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: 'app-1',
    athleteId: 'athlete-4',
    athlete: {
      id: 'athlete-4',
      userId: 'user-athlete-4',
      name: 'Morgan Wells',
      avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400&h=400&fit=crop',
      age: 21,
      location: 'Nashville, TN',
      primaryEvent: 'shot_put',
      secondaryEvents: [],
      prs: { shot_put: '14.80m' },
      level: 'collegiate',
      schoolOrClub: 'Vanderbilt University',
      trainingAge: 3,
      goals: 'Conference qualifier. Work on glide mechanics.',
      coachingPreferences: ['video_critique', 'programming'],
      budget: '$150-250/month',
      bio: '',
      videos: [],
      visibilitySettings: { publicProfile: true, showPRs: true, showVideos: true },
      createdAt: '2024-04-02',
    },
    coachId: 'coach-1',
    packageId: 'pkg-1',
    answers: {
      'What are your current personal records for your primary events?': '14.80m shot put (glide). Competed indoors this winter, outdoor season starting next week.',
      'What are your goals for the next 12 months?': 'Want to qualify for conference championships. Need to get to 15.50m minimum. Glide mechanics are inconsistent under competition pressure.',
      'Describe your current training setup — access to implements, lifting facility, track, etc.': 'Access to D1 facility at school. Shot, discus, weight room, outdoor ring. Training 5x per week.',
    },
    status: 'pending',
    submittedAt: '2024-04-20T14:30:00Z',
  },
  {
    id: 'app-2',
    athleteId: 'athlete-5',
    athlete: {
      id: 'athlete-5',
      userId: 'user-athlete-5',
      name: 'Ethan Marsh',
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop',
      age: 24,
      location: 'Denver, CO',
      primaryEvent: 'discus',
      secondaryEvents: ['shot_put'],
      prs: { discus: '50.20m', shot_put: '16.10m' },
      level: 'post_collegiate',
      schoolOrClub: 'Rocky Mountain TC',
      trainingAge: 6,
      goals: 'Push past 55m in discus. Better hip separation.',
      coachingPreferences: ['full_coaching'],
      budget: '$200-350/month',
      bio: '',
      videos: [],
      visibilitySettings: { publicProfile: true, showPRs: true, showVideos: false },
      createdAt: '2024-03-28',
    },
    coachId: 'coach-1',
    packageId: 'pkg-1',
    answers: {
      'What are your current personal records for your primary events?': 'Discus: 50.20m (rotational). Shot: 16.10m. Both set last fall.',
      'What are your goals for the next 12 months?': '55m discus is the milestone. I know it is a technique issue — I lose the left side through the finish.',
      'Describe your current training setup — access to implements, lifting facility, track, etc.': 'Full access to throwing facility at local college by arrangement. Lifting at commercial gym.',
    },
    status: 'pending',
    submittedAt: '2024-04-18T09:15:00Z',
  },
]

export const MOCK_PROGRAMS: TrainingProgram[] = [
  {
    id: 'prog-1',
    coachId: 'coach-1',
    name: 'Outdoor Season — Phase 2 Block (Shot + Discus)',
    description: 'Four-week competition preparation block. Focus on speed-strength and competition readiness.',
    targetEvent: ['shot_put', 'discus'],
    level: 'collegiate / post-collegiate',
    weeks: [
      {
        weekNumber: 1,
        theme: 'Activation and prime',
        sessions: [
          {
            id: 'sess-1',
            day: 'Monday',
            title: 'Speed-strength — Shot',
            type: 'throws',
            exercises: [
              { name: 'Standing shot — 5kg', sets: 4, reps: '3', notes: 'Max intent, not max effort' },
              { name: 'Full approach — shot', sets: 6, reps: '1', notes: 'Focus on finish position' },
              { name: 'Reverse standing — 7kg', sets: 3, reps: '2' },
            ],
          },
          {
            id: 'sess-2',
            day: 'Wednesday',
            title: 'Lower body — moderate',
            type: 'lifting',
            exercises: [
              { name: 'Back squat', sets: 4, reps: '4', weight: '80% 1RM' },
              { name: 'Romanian deadlift', sets: 3, reps: '5', weight: '70%' },
              { name: 'Box jump', sets: 4, reps: '3' },
            ],
          },
          {
            id: 'sess-3',
            day: 'Friday',
            title: 'Full session — discus',
            type: 'throws',
            exercises: [
              { name: 'Drill sequence — winding', sets: 2, reps: '5 each' },
              { name: 'Full discus — competition implement', sets: 8, reps: '1', notes: 'Video throws 4 and 6' },
            ],
          },
        ],
      },
    ],
    isTemplate: false,
    assignedAthletes: ['athlete-1', 'athlete-3'],
    createdAt: '2024-03-01',
  },
]

export const MOCK_VIDEOS: VideoSubmission[] = [
  {
    id: 'vid-1',
    athleteId: 'athlete-1',
    coachId: 'coach-1',
    title: 'Shot put — indoor meet, attempt 3',
    event: 'shot_put',
    thumbnailUrl: 'https://images.unsplash.com/photo-1541534741688-6078c6bfb5c5?w=600&h=340&fit=crop',
    videoUrl: '#',
    uploadedAt: '2024-04-21T10:00:00Z',
    status: 'pending_review',
  },
  {
    id: 'vid-2',
    athleteId: 'athlete-3',
    coachId: 'coach-1',
    title: 'Discus — training session, full approach',
    event: 'discus',
    thumbnailUrl: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&h=340&fit=crop',
    videoUrl: '#',
    uploadedAt: '2024-04-19T16:30:00Z',
    status: 'reviewed',
    feedback: {
      id: 'fb-1',
      coachId: 'coach-1',
      text: 'Much better left side control through the release. You are still breaking the left knee too early — cue: "land and hold" on the left. See drill below.',
      keyPoints: [
        'Left side too soft through release — practice standing throws with left arm pinned',
        'Release angle looks correct',
        'Foot timing on entry step needs adjustment — you are crowding the center',
      ],
      drills: ['Left-arm-pinned standing throws x 5', 'Half-turn drill focusing on left side stability'],
      sentAt: '2024-04-20T11:00:00Z',
    },
  },
  {
    id: 'vid-3',
    athleteId: 'athlete-2',
    coachId: 'coach-2',
    title: 'Hammer — turn 3 entry',
    event: 'hammer',
    thumbnailUrl: 'https://images.unsplash.com/photo-1461896836934-ffe607ba8211?w=600&h=340&fit=crop',
    videoUrl: '#',
    uploadedAt: '2024-04-22T08:45:00Z',
    status: 'pending_review',
  },
]

export const MOCK_THREADS: MessageThread[] = [
  {
    id: 'thread-1',
    participants: ['coach-1', 'athlete-1'],
    coachId: 'coach-1',
    athleteId: 'athlete-1',
    lastMessage: {
      id: 'msg-3',
      threadId: 'thread-1',
      senderId: 'coach-1',
      text: 'Check the session notes for Friday — I updated the implements. Use the 6.25kg for the first 4, then move to competition weight for the last 4.',
      sentAt: '2024-04-22T09:12:00Z',
    },
    unreadCount: 1,
    updatedAt: '2024-04-22T09:12:00Z',
  },
  {
    id: 'thread-2',
    participants: ['coach-1', 'athlete-3'],
    coachId: 'coach-1',
    athleteId: 'athlete-3',
    lastMessage: {
      id: 'msg-6',
      threadId: 'thread-2',
      senderId: 'athlete-3',
      text: 'Reviewed the feedback. Going to work the standing throws with left arm pinned tomorrow. Should I film?',
      sentAt: '2024-04-21T20:45:00Z',
    },
    unreadCount: 1,
    updatedAt: '2024-04-21T20:45:00Z',
  },
]

export const MOCK_BILLING: BillingSummary = {
  coachId: 'coach-1',
  monthlyRecurring: 2280,
  activeSubscriptions: 9,
  pendingPayouts: 1840,
  totalEarnings: 18400,
  platformFeePercent: 8,
  nextPayoutDate: '2024-05-01',
  recentTransactions: [
    { id: 'tx-1', athleteName: 'Tyler Rhodes', amount: 285, type: 'payment', date: '2024-04-15', status: 'completed' },
    { id: 'tx-2', athleteName: 'Daniel Farris', amount: 285, type: 'payment', date: '2024-04-15', status: 'completed' },
    { id: 'tx-3', athleteName: 'Coach Payout', amount: 1840, type: 'payout', date: '2024-04-01', status: 'completed' },
    { id: 'tx-4', athleteName: 'Marcus V.', amount: 285, type: 'payment', date: '2024-04-14', status: 'completed' },
    { id: 'tx-5', athleteName: 'Alexis R.', amount: 95, type: 'payment', date: '2024-04-14', status: 'pending' },
  ],
}

export const EVENT_LABELS: Record<string, string> = {
  shot_put: 'Shot Put',
  discus: 'Discus',
  hammer: 'Hammer',
  javelin: 'Javelin',
}

export const LEVEL_LABELS: Record<string, string> = {
  youth: 'Youth',
  high_school: 'High School',
  collegiate: 'Collegiate',
  post_collegiate: 'Post-Collegiate',
  professional: 'Professional',
}
